Test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('Testpage/', include('Testpage.urls')),
    path('admin/', admin.site.urls),
]

Testpage/urls.py
from django.urls import path
from . import views

app_name = 'Testpage'
urlpatterns = [
    path('', views.index, name='index'),
    path('form/', views.register_user, name='form'),
    path('show/', views.show_users, name='show'),
]

Testpage/models.py
from django.db import models


class UserProfile(models.Model):
    Name = models.CharField(max_length=200)
    Mail = models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.Name

Testpage/forms.py
from django import forms
from .models import UserProfile


class RegisterForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['Name', 'Mail']

Testpage/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from .models import UserProfile
from django.http import HttpResponse


def index(request):
    return render(request, 'Testpage/index.html')


def register_user(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_reg = UserProfile()
            new_reg.Name = request.POST.get("Name")
            new_reg.Mail = request.POST.get("Mail")
            new_reg.save()
            return redirect('Testpage:index')
        else:
            return HttpResponse('errors')
    else:
        form = RegisterForm()

    return render(request, 'Testpage/form.html', {'form': form})


def show_users(request):
    users = UserProfile.objects.all()[:10]

    return render(request, 'Testpage/show.html', {'users': users})

Testpage/templates/Testpage/form.html
<form method="POST" action="{% url 'Testpage:form' %}">
    {% csrf_token %}
    <div class="field">
        <label>First name: </label>
        {{ form.Name }}
    </div>
    <div class="field">
        <label>Mail: </label>
        {{ form.Mail }}
    </div>
    </div>
    <input type="submit" value="Submit">
</form>

Testpage/templates/Testpage/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register test page</title>
</head>
<body>
    <a href="/Testpage/form">Form</a>
    <a href="/Testpage/show">Show</a>
</body>
</html>

Testpage/templates/Testpage/show.html
<ol>
    {% for user in users %}
        <li>
            {{ user.Name }}
            {{ user.Mail }}
            {{ user.date }}
        </li>
    {% endfor %}
</ol>
<a href="/Testpage/">Index</a>